title: "Weerit's Resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Weerit Nopcharoenwong"
resume_title:                   "About Me"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "weeritn@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "(385) 528-7373"
resume_contact_address:         "840 S 850 E, Centerville, Utah, United States"

resume_header_contact_info:     "840 S 850 E, Centerville, Utah, United States • (385) 528-7373 • weeritn@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>I am a third year Computer Science student at the University of Utah. I'm interested in software development, full stack engineering, and anything else tech related. Outside of software and technology, I love fishing, building cars, and meeting new people. I'm seeking an internship for 2024 and would love to hear about any opportunies.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/weeritn"
  # resume_twitter_url:           "insert twitter here"
  # resume_dribbble_url:          ""insert whatever here"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/weeritn"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "insert website here"
  # resume_medium_url:            "insert medium here"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
